[package]
name = "omafanctrl-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "CLI client for omafanctrl, designed for Hyprland hotkeys"

[[bin]]
name = "omafanctrl"
path = "src/main.rs"

[dependencies]
omafanctrl-core.workspace = true
