[package]
name = "omafanctrl-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "CLI client and bar status module for omafanctrl"

[lib]
name = "omafanctrl_cli"
path = "src/lib.rs"

[[bin]]
name = "omafanctrl"
path = "src/main.rs"

[[bin]]
name = "omafanctrl-status"
path = "src/bin/omafanctrl-status.rs"

[dependencies]
omafanctrl-core.workspace = true
anyhow.workspace = true
clap.workspace = true
tokio.workspace = true
zbus.workspace = true
serde.workspace = true
serde_json.workspace = true
